function table(){
    return(
        <div>
            <table>
                <tr>
                    <td>
                        cookies
                    </td>
                    <td>
                        baklava
                    </td>
                    <td>
                        rasmalai
                    </td>
                </tr>
                <tr>
                    <td>
                        hiking
                    </td>
                    <td>
                        swimming
                    </td>
                    <td>
                        diving
                    </td>
                </tr>
                <tr>
                    <td>
                        reading
                    </td>
                    <td>
                        painting
                    </td>
                    <td>
                        crafting
                    </td>
                </tr>
            </table>
        </div>
    )
}

export default table;